class_name Balance
extends RefCounted

const PLAYER_VERTICAL_SPEED := 180.0
const PLAYER_HORIZONTAL_SPEED := 680.0
const PLAYER_HORIZONTAL_ACCELERATION := 6000.0
const SPIDER_SPEED_RATIO := 0.88
const SPIDER_RAMP_FULL_DISTANCE := 288.0
const START_DISTANCE := 180.0
const CATCH_DISTANCE := 28.0
const GAUGE_MAX_DISTANCE := 360.0
const ROUTE_X := [-240.0, 0.0, 240.0]
const STAGE_DURATION_SECONDS := 30.0
const STAGE_COUNT := 5
const STAGE_HEIGHT := PLAYER_VERTICAL_SPEED * STAGE_DURATION_SECONDS
const PATTERN_SEED := 20260923
const BEAN_WARNING_SECONDS := 0.60
const BEAN_KNOCKBACK_SECONDS := 0.36
const BEAN_STUN_SECONDS := 0.18
const BEAN_KNOCKBACK_SPEED := 180.0
const BEAN_FALL_SPEED := 420.0
const BEAN_SPAWN_LEAD_PX := 270.0
const BEAN_HIT_RADIUS := 30.0
const SPIDER_BOOST_RATIO := 1.15
const SPIDER_BOOST_SECONDS := 2.0
const ROUTE_DEAD_END_WARNING_SECONDS := 1.20
const ROUTE_DEAD_END_WARNING_PX := PLAYER_VERTICAL_SPEED * ROUTE_DEAD_END_WARNING_SECONDS
const TIME_WINGS_STAGE := 5
const TIME_WINGS_SECONDS := 10.0
const TIME_WINGS_SLOW_SCALE := 0.5
const TUTORIAL_SECONDS := 3.0
const STAGE_COMPLETE_SECONDS := 1.5
const TOUCH_BUTTON_MIN_PX := 44.0
const PIXELS_PER_METER := 18.0
const GAUGE_THRESHOLDS := {
	"GREEN": 0.20,
	"YELLOW": 0.40,
	"ORANGE": 0.60,
	"RED": 0.80,
	"DANGER": 1.00,
}
